services:
    postgres:
        image: postgres
        environment: 
            - POSTGRES_PASSWORD=123456
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
    mongodb: 
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=mongopw
        command: ["mongod", "--bind_ip", "0.0.0.0"]
        ports: 
            - 27017:27017
        volumes: 
            - mongodata:/var/lib/mongodb/data 
    rabbitmq: 
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
    auction-svc:
        image: invaSh/auction-svc:latest
        build: 
            context: .
            dockerfile: src/AuctionService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80   
            - RabbitMq__Host=rabbitmq
            - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=123456;Database=auctions
            - IdentityServiceUrl=http://identity-svc 
        ports:
            - 5001:80
        depends_on:
            - postgres
            - rabbitmq
    search-svc:
        image: invaSh/search-svc:latest
        build: 
            context: .
            dockerfile: src/SearchService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80   
            - RabbitMq__Host=rabbitmq
            - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
        ports:
            - 7002:80
        depends_on:
            - mongodb
            - rabbitmq
    identity-svc:
        image: invaSh/identity-svc:latest
        build: 
            context: .
            dockerfile: src/IdentityService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=http://+:80
            - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=123456;Database=identity
        ports:
            - 5000:80
        depends_on:
            - postgres   
    gateway-svc:
        image: invaSh/gateway-svc:latest
        build: 
            context: .
            dockerfile: src/GatewayService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=http://+:80
        ports:
            - 6001:80 
    bid-svc:
        image: invaSh/bid-svc:latest
        build: 
            context: .
            dockerfile: src/BiddingService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80   
            - RabbitMq__Host=rabbitmq
            - ConnectionStrings__BidConnection=mongodb://root:mongopw@mongodb
            - IdentityServiceUrl=http://identity-svc 
        ports:
            - 7003:80
        depends_on:
            - mongodb
            - rabbitmq
    notify-svc:
        image: invaSh/notify-svc:latest
        build: 
            context: .
            dockerfile: src/NotificationService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80   
            - RabbitMq__Host=rabbitmq
        ports:
            - 7004:80
        depends_on:
            - rabbitmq
volumes:
    pgdata:
    mongodata: