
import "./globals.css";
import App from "../pages/_app"
export const metadata = {
  title: "Arcadia Auction House",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <App children={children} />
      </body>
    </html>
  );
}
