import "./globals.css";
import Navbar from "./components/nav/Navbar";
import AdminNavbar from "@/app/components/admin/Navbar";
import { getSession } from "./actions/authActions";
import Footer from "./components/Footer";

export const metadata = {
  title: "Arcadia Auction House",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getSession();
  let isAdmin;
  let showNavbar = true;


  if (session && session.user) {
    const user = session.user;
    isAdmin = user.roles.includes("Admin") || user.roles.includes("Manager");
  }

  return (
    <html lang="en">
      <body className={isAdmin ? "grid grid-cols-12" : ""}>
        {showNavbar && (isAdmin ? <AdminNavbar /> : <Navbar />)}
        <main className={isAdmin ? "col-span-10 col-start-3 font-syne" : ""}>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
